
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb           
    container_name: mariadb
    restart: on-failure
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p${SQL_ROOT_PWD}"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    restart: on-failure
    networks:
      - inception
    command: ["--requirepass", "${REDIS_PWD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PWD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
  wordpress:
    build: ./requirements/wordpress
    image: wordpress        
    container_name: wordpress
    restart: on-failure
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pgrep", "php-fpm8.2"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 120s
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
  nginx:
    build: ./requirements/nginx
    image: nginx            
    container_name: nginx
    restart: on-failure
    ports:
      - "443:443"            
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    container_name: ftp
    restart: on-failure
    ports:
      - "21:21"
      - "50000-50100:50000-50100"
    volumes:
      - wp-data:/var/www/html
    env_file: .env
  website:
    build: ./requirements/bonus/website
    image: website
    container_name: website
    restart: on-failure
    networks:
      - inception
  backup:
    container_name: backup
    build: requirements/bonus/backup
    image: backup
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - db-data:/db-data
      - backup-data:/backup
    restart: on-failure
networks:
  inception:

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oben-jha/data/mariadb  
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oben-jha/data/wordpress
  backup-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oben-jha/data/backup