
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb           
    container_name: mariadb
    restart: always
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - inception
  redis:
    build: ./requirements/redis
    image: redis
    container_name: redis
    restart: always
    networks:
      - inception
  wordpress:
    build: ./requirements/wordpress
    image: wordpress        
    container_name: wordpress
    restart: always
    env_file: .env
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
  adminer:
    build: ./requirements/adminer
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
  nginx:
    build: ./requirements/nginx
    image: nginx            
    container_name: nginx
    restart: always
    ports:
      - "443:443"            
    depends_on:
      - wordpress
    volumes:
      - wp-data:/var/www/html
    networks:
      - inception
  ftp:
    build: ./requirements/ftp
    image: ftp
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "50000-50100:50000-50100"
    volumes:
      - wp-data:/var/www/html
    env_file: .env
networks:
  inception:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oben-jha/data/mariadb  
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/oben-jha/data/wordpress