ServerName          "Inception FTP Server"
ServerType          standalone
DefaultServer       on

# Standard FTP Port
Port                21

# Passive mode configuration
PassivePorts        50000 50100
MasqueradeAddress   oben-jha.42.fr

# Disable IPv6
UseIPv6             off

# Base permissions
Umask               022

# Number of allowed connections
MaxInstances        30

# The user/group ProFTPD runs as by default
User                proftpd
Group               nogroup

# Lock the user into the WordPress directory
DefaultRoot         /var/www/html

# Allow overwriting files
AllowOverwrite      yes

# Don't require a valid shell to log in
RequireValidShell   no

# Block anonymous login completely
<Anonymous ~ftp>
  DenyAll
</Anonymous>

# TLS WILL GO HERE LATER
# <IfModule mod_tls.c>
#   TLSEngine on
#   ...
# </IfModule>